# Generated by Django 5.1.5 on 2025-02-05 02:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='movie',
            name='tmdb_rating',
            field=models.FloatField(default=0),
        ),
    ]
