# Generated by Django 5.1.5 on 2025-02-05 17:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0002_movie_tmdb_rating'),
    ]

    operations = [
        migrations.AlterField(
            model_name='movie',
            name='duration',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
