# Generated by Django 5.1.7 on 2025-04-06 20:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0005_trendingreview'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='trendingreview',
            options={'ordering': ['-rating'], 'verbose_name_plural': 'Trending Reviews'},
        ),
        migrations.AddField(
            model_name='trendingreview',
            name='genres',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='trendingreview',
            name='overview',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='trendingreview',
            name='poster_path',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='trendingreview',
            name='release_date',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='trendingreview',
            name='title',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='trendingreview',
            name='updated_at',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AlterField(
            model_name='trendingreview',
            name='tmdb_id',
            field=models.IntegerField(unique=True),
        ),
    ]
